# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: API Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # schedule:
  #   # Runs twice: daily at 2 AM UTC and Monday/Thursday at 2 PM UTC
  #   - cron: '0 2 * * *'     # Daily at 2 AM UTC
  #   - cron: '0 14 * * 1,4'  # Monday and Thursday at 2 PM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    
    
    - name: Run API Tests
      run: mvn clean test -Dsuite=suite -X
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-output/reports/
          target/surefire-reports/
          logs/
    
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

